'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System

Namespace HelloWorld
    
    Public Class Program
        
        Public Shared Sub Main()
            Console.WriteLine("Hello, World!")
        End Sub
    End Class
End Namespace
