//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelloWorld {
    using System;
    
    
    public class Program {
        
        public static void Main() {
            Console.WriteLine("Hello, World!");
        }
    }
}
